-- INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES(Mr.Chocolate, 2, male, brown, docile, true);
-- INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES(Rowdy, NULL, NULL, NULL, NULL, NULL);
-- INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES(Tabitha, NULL, NULL, NULL, NULL, NULL);
-- INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES(Sergeant Brown, NULL, NULL, NULL, NULL, NULL);
-- INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES(Melissa, NULL, NULL, NULL, NULL, NULL);
-- INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES(Grinch, NULL, NULL, NULL, NULL, NULL);
-- INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES(Wendy, NULL, NULL, NULL, NULL, NULL);
-- INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES(NULL, NULL, NULL, NULL, NULL, NULL);